version: '3'
services:


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: pbna_pguser
      POSTGRES_PASSWORD: pbna_pgpw
      POSTGRES_DB: pbna_pgdb
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data


  redis:
    image: redis
    container_name: redis
    # use when backend is running in container
    expose:
      - 6379
    # used when backend is running locally
    ports:
      - "6379:6379"      


  keystone:
    container_name: keystone
    build: 
      context: ./keystone
      dockerfile: keystone.Dockerfile
    #command: "npm run start"
    command: "npm run dev"
    #command: tail -f /dev/null
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      PORT: 3000   
      # NODE_ENV: development
      # values should come from postgres env...
      DATABASE_URL: postgres://pbna_pguser:pbna_pgpw@postgres/pbna_pgdb
    volumes:
      - type: bind
        source: ./common
        target: /code/common
    links:
      - redis


  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: frontend.Dockerfile
    command: "npm run start"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080   
      GRAPHQL_API_URL: "http://backend:3000/api/graphql"
    volumes:
      - type: bind
        source: ./frontend/src
        target: /code/src


  llama:
    container_name: llama
    build: 
      context: ./node-llama
      dockerfile: node-llama.Dockerfile
    links:
      - redis
      - keystone
    volumes:
      - type: bind
        source: ./common
        target: /code/common
      - type: bind
        source: ./models
        target: /code/models           
      - type: bind
        source: ./node-llama/src
        target: /code/src        
    command: npm run dev

  tesseract:
    container_name: tesseract
    build: 
      context: ./tesseract
      dockerfile: tesseract.Dockerfile
    links:
      - redis
      - keystone
    volumes:
      - type: bind
        source: ./common
        target: /code/common
      - type: bind
        source: ./tesseract/src
        target: /code/src
    # command: tail -f /dev/null
    command: npm run dev

volumes:
  pg-data:
