import { list } from "@keystone-6/core";
import { allowAll } from "@keystone-6/core/access";
import {
  text,
  relationship,
  timestamp,
  integer,
  calendarDay,
  decimal,
  select,
  checkbox,
} from "@keystone-6/core/fields";

import { isAdmin, isOwner, isUser } from "../roles";
import type { AppContext } from "../../context";
import { runOrchestrator } from "../../helpers/orchestrator";
import { augmentContext } from "../../context";

export function ensureSessionData(session) {
  if (!session?.data) {
    throw new Error("Unauthenticated");
  }

  return true;
}

export const Invoice = list({
  access: {
    operation: {
      query: ({ session }) => ensureSessionData(session),
      create: ({ session }) => ensureSessionData(session),
      update: ({ session }) => ensureSessionData(session),
      delete: ({ session }) => ensureSessionData(session),
    },
    filter: {
      query: ({ session, context, listKey, operation }) => {
        //console.log(session)

        // for debugging, this essentially turns of access control
        //return true

        if (isAdmin({ session })) {
          return true;
        }

        if (isOwner({ session })) {
          return {
            owner: {
              id: {
                equals: session?.data.organization.id,
              },
            }, // TODO: add support for mutliple orgs
          };
        }

        return false;
      },
    },
  },
  fields: {
    createdAt: timestamp({
      defaultValue: { kind: "now" },
      validation: { isRequired: true },
      ui: {
        createView: {
          fieldMode: "hidden",
        },
      },
    }),

    createdBy: relationship({
      ref: "User",
      ui: {
        hideCreate: true,
      },
    }),

    owner: relationship({
      ref: "Organization",
      ui: {
        hideCreate: true,
      },
    }),

    accountingPeriod: relationship({
      ref: "AccountingPeriod",
    }),

    date: calendarDay({
      label: "Transaction Date",
    }),

    // Used for filteringing / grouping invoices in the UI
    type: select({
      options: [
        { label: "Unverified", value: "unverified" },
        { label: "Outgoing", value: "outgoing" },
        { label: "Incoming", value: "incoming" },
      ],
      validation: { isRequired: true },
    }),

    // The assistant to run on this invoice, if any (an assistant is a predefined orchestrator)
    orchestrator: relationship({
      ref: "Orchestrator",
    }),

    status: select({
      options: [
        { label: "Draft", value: "draft" }, // initial status for manual invoices
        { label: "Pending", value: "pending" }, // pending assistant processing
        { label: "Processing", value: "processing" }, // actively processed by assistant
        { label: "Awaiting verification", value: "awaiting_verification" }, // processed by assistant, needs user verification
        { label: "Verified", value: "verified" }, // verified by user (manual invoices are automatically verified unless in draft status)
        { label: "Failed", value: "failed" }, // verified by user (manual invoices are automatically verified unless in draft status)
      ],
      defaultValue: "draft",
      ui: {
        displayMode: "segmented-control", // or 'select'
      },
    }),

    description: text(),

    invoiceNumber: text(),

    totalAmount: decimal({
      scale: 2,
      //defaultValue: "0",
    }),

    vatAmount: decimal({
      scale: 2,
      //defaultValue: "0",
    }),

    attachments: relationship({
      ref: "Attachment",
      many: true,
    }),

    entry: relationship({
      ref: "Entry",
      many: false,
    }),

    isPaid: checkbox({ defaultValue: false }),

    // true if invoice is generated by the assistant
    isGenerated: checkbox({ defaultValue: false }),
  },
  ui: {
    label: "Invoice",
    listView: {
      initialColumns: [
        "invoiceNumber",
        "status",
        "type",
        "orchestrator",
        "date",
        "description",
        "accountingPeriod",
      ],
    },
  },
  hooks: {
    beforeOperation: {
      create: async ({ context, resolvedData }) => {
        resolvedData.createdBy = {
          connect: { id: context.session.data.id },
        };

        resolvedData.owner = {
          connect: { id: context.session.data.organization.id },
        };
      },
    },
    afterOperation: {
      create: async ({ item, context, operation, inputData }) => {
        try {
          // for new invoices, check if we need to run an assistant
          if (item.orchestratorId && item.status === "pending") {
            // find orchestrators for this assistant
            const orchestrators = await context.query.Orchestrator.findMany({
              where: {
                triggerEvent: {
                  equals: "invoice:afterOperation:create",
                },
                AND: { isEnabled: { equals: true } },
              },
              query: `id name`,
            });

            console.log(
              `Found ${orchestrators.length} orchestrators for invoice ${item.id}`
            );

            // run orchestrators
            for (const orchestrator of orchestrators) {
              console.log(
                `invoice afterOperation create: running orchestrator ${orchestrator.name} for invoice ${item.id}`
              );

              console.log(orchestrator);

              await context.db.Invoice.updateOne({
                where: { id: item.id },
                data: {
                  status: "processing",
                },
              });

              await runOrchestrator({
                context,
                orchestratorId: orchestrator.id,
                payload: { invoiceId: item.id },
              });
            }
          }

          const channelName = `ON_INVOICE:${item?.createdById}`;

          const ctx = augmentContext(context);
          await ctx.pubsub.publish(channelName, { onInvoice: { ...item } });
        } catch (e) {
          await context.db.Invoice.updateOne({
            where: { id: item.id },
            data: {
              status: "failed",
            },
          });

          console.log(e);
        }
      },
      update: async ({ item, context, operation, inputData, originalItem }) => {
        const ctx = augmentContext(context);
        await ctx.pubsub.publish(`ON_INVOICE:${item?.createdById}`, {
          onInvoice: { ...item },
        });
      },
    },
  },
});
